In [ ]:
pip install numpy

Question 1:

In [ ]:
import numpy as np
arr = np.arange(2, 50, 3)
print (arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


Question 2:

In [ ]:
import numpy as np
list_1 = []                                            #creating empty lists
list_2 = []

for i in range(5):                                     #values for list_1
  x = int(input("\n Enter the value for list_1:"))
  list_1.append(x)

for i in range(5):
  x = int(input("\n Enter the value for list_2:"))     #values for list_2
  list_2.append(x)

arr_1 = np.array(list_1)                               #converting list to numpy array 
arr_2 = np.array(list_2)

arr = np.concatenate((arr_1,arr_2))                   #concatenate arr_1 and arr_2
print("\n concatenated array:",arr)

sort_arr = np.sort(arr)
print("\n sorted array:",sort_arr)                    #sorting sort_arr





 Enter the value for list_1:3

 Enter the value for list_1:2

 Enter the value for list_1:7

 Enter the value for list_1:5

 Enter the value for list_1:1

 Enter the value for list_2:7

 Enter the value for list_2:9

 Enter the value for list_2:4

 Enter the value for list_2:6

 Enter the value for list_2:8

 concatenated array: [3 2 7 5 1 7 9 4 6 8]

 sorted array: [1 2 3 4 5 6 7 7 8 9]


Question 3:

An array class in numpy called as ndarry.

Snippet for finding dimension:
 Arrayname.ndim

Snippet for finding size:
  Arrayname.size  

In [14]:
import numpy as np
arr = np.array([[1,2,4],[5,3,4]])
arr.shape

print("\n Dimension in array:",arr.ndim)

print("\n Size of the array:",arr.size)




 Dimension in array: 2

 Size of the array: 6


Question 4:

                            Newaxis Snippet 






In [22]:
import numpy as np

arr = np.arange(6)                      #creating a 1D array
print("\n shape of array:",arr.shape)

row_arr = arr[np.newaxis,:]              #converting to 2D array in row major
print("\nShape of 2D array in row major :",row_arr.shape)

col_arr = arr[:,np.newaxis]              #converting to 2D array in column major
print("\n Shape of 2D array in coloumn major:",col_arr.shape )




 shape of array: (6,)

Shape of 2D array in row major : (1, 6)

 Shape of 2D array in coloumn major: (6, 1)


                                  **expand_dims** snippet

In [39]:
import numpy as np

arr = np.arange(6)
print("\n shape of array :",arr.shape)

row_arr = np.expand_dims(arr,axis=0)
print("\n Shape of 2d Array in row major",row_arr.shape)

col_arr = np.expand_dims(arr,axis=1)
print("\n Shape of 2d Array in column major",col_arr.shape)




 shape of array : (6,)

 Shape of 2d Array in row major (1, 6)

 Shape of 2d Array in column major (6, 1)


Question 5:
 
 Hint: Use vstack(), hstack()





In [36]:
import numpy as np

arr_1 = np.square([1,2,3,4,5])
arr_2 = np.square([6,7,8,9,10])

print("\nvertical Append:",np.vstack((arr_1,arr_2)))
print("\n horizontal Append:",np.hstack((arr_1,arr_2)))                  


vertical Append: [[  1   4   9  16  25]
 [ 36  49  64  81 100]]

 horizontal Append: [  1   4   9  16  25  36  49  64  81 100]


Question 6:


How to get unique items and counts of unique items?

  unique method is used to get the unique values from the list and return count attribute of unique method return the count of unique value from the list.

In [66]:
def unique(list1):
  x = np.array(list1)
  print(np.unique(x))

list1 = [1,2,3,5,3,4]
print("The unique values from 1st list is:")
unique(list1)

new_set = set(list1)
print("\n The count of the list1 is",len(new_set))



The unique values from 1st list is:
[1 2 3 4 5]

 The count of the list1 is 5
